image: ubuntu:latest

variables:
  BUILD_TYPE: Release

build:
  stage: build
  # instead of calling g++ directly you can also use some build toolkit like make
  # install the necessary build tools when needed
  before_script:
    - rm -Rf build
    - apt update && apt -y install cmake build-essential
    - apt install -y aptitude && aptitude install -y libeigen3-dev libceres-dev libgtest-dev
    - mkdir $CI_PROJECT_DIR/build && cmake -B $CI_PROJECT_DIR/build -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DBUILD_TESTS=ON -DBUILD_EXECUTABLES=OFF
    - cmake --build $CI_PROJECT_DIR/build --config $BUILD_TYPE
  script:
    - cd build && ctest -C $BUILD_TYPE
  cache:
    paths:
      - "build/*.o"
